### ISSUE TITLE
Querying by hbz ID with name parameter is broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#283] opened 2016-01-20 09:08 UTC
@jschnasse reported on 20.01.2016 08:51:

> Dringend:
> 
> die Suche nach HT-Nummern funktioniert nicht mehr wie früher. Früher 
> haben wir bei der Suche nach einer HT-Nummer genau einen Einzeltreffer 
> erhalten, nun erhalten wir ein Liste mit sehr seltsamen Einträgen. Da 
> die Suchanfrage von Felix kommt, kann ich Sie hier nicht so einfach mit 
> anhängen bzw. werde das an unten beigefügtem Ticket noch tun. Im 
> Zeitraum 2016-01-20 8:49 sollte sich aber eine Anfrage von 
> repository.publisso.de (agent: drupal) in euren logs finden.

**Comment by acka47** [comment] 2016-01-20 09:09
@literarymachine clarified:

> ich gehe bei der Suche über den "name"-Parameter:
> 
> http://lobid.org/resource?name=HT015334072
> 
> Tut in der Tat nicht mehr so, wie früher. Wird da vielleicht 
> fälschlicherweise die HT-Nummer in Tokens übersetzt?

**Comment by dr0i** [comment] 2016-01-20 11:11
1. Cloned a new repo `lobid-hbz-issue-283` and started this as a lobid-api running on its own port. It uses the new index (with the new index profile to enable Umlaute etc.). This api is now used by nwbib.
2. Configured the productive lobid-api to use the index with the old index config so that `edoweb` can use their `name` parameter as used to.

*Both* indices are updated daily.
Now is time to examine what went wrong for the `name` parameter.

**Comment by dr0i** [comment] 2016-01-20 13:43
I assume the cause of the issue the usage of `"tokenizer" : "letter"` for the newly `german_analyzer` introduced with hbz/nwbib#208: it splits a search query like `"HT1234"` into `"HT" and "1234"`. As there are resources which has the `HT` as title, e.g. http://lobid.org/resource?id=HT015334072 a HT-query would always also hit the forementioned resource (amongst others).
Question is: is this tokenizer really needed?
And, of course, what is also true:
the usage of the `name` parameter to make identifier queries should be considered harmful. The proper parameter is `id`, and this was working as expected all along the way.

**Comment by literarymachine** [comment] 2016-01-20 13:49
> the usage of the name parameter to make identifier queries should be considered harmful. The proper parameter is id, and this was working as expected all along the way.

I can't find the issue any more (maybe it was in some old repo?), but in edoweb we needed a way to query for either `name` or `id`. via the same parameter. This is why back then you added `hbzID` when querying for `name`.

**Comment by jschnasse** [comment] 2016-01-20 13:53
in api 2.0 it will be sensible to switch to ?q endpoint and teach our users how to query a single field. At the moment ?name is best we can get from lobid without spoiling the internal url-like field identifiers.

**Comment by dr0i** [comment] 2016-01-20 14:01
> I can't find the issue any more  

I can't also but now you mentioned it: vaguely I remember , there was something !

**Comment by dr0i** [comment] 2016-01-20 15:50
Indexed small test set with


a) `tokenizer: letter`:
http://test.lobid.org/resource?name=HT017250960 gave *two* results (one with HT as title (i.e. http://lobid.org/resource/HT014211528 ))


b) `tokenizer: standard`:
Try http://test.lobid.org/resource?name=HT017250960 (which reveals *one* result) and try http://test.lobid.org/resource?name=HT (which reveals an other resource having title `HT`). 

So with the standard-tokenizer the HT-ids are not splitted. This should be our solution.

Question is:
Does anyone needs the letter-tokenizer? [Automatic tests in the lobid API are fine.](https://github.com/hbz/lobid/pull/284)

**Comment by fsteeg** [comment] 2016-01-25 08:41
> Question is:
> Does anyone needs the letter-tokenizer ? Automatic tests in the lobid API are fine, though. Ping also @fsteeg.

I don't think so, fix looks very good. I just used the wrong tokenizer when setting up the German analyzer.

**Comment by dr0i** [comment] 2016-01-25 10:32
Deployed to production, closing.

**Closed by dr0i** 2016-01-25 10:32 UTC
Labels: bug

**Comment by dr0i** [comment] 2016-07-13 09:04
> Cloned a new repo lobid-hbz-issue-283 and started this as a lobid-api running on its own port.

Now it's time to stop this instance ;)
Took it out of monit's watch and killed it. Got us 1GB RAM back :)
