### ISSUE TITLE
Some gnd labels missing

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#149] opened 2015-05-25 12:02 UTC
http://test.lobid.org/resource/HT018401863/about Only an editor is given but the label isn't included.

**Comment by dr0i** [comment] 2015-05-27 16:05
Deployed to staging and production.

**Comment by acka47** [comment] 2015-05-28 08:36
Works on test but not on production, see the nwbib entry at http://lobid.org/nwbib/HT018401863.

**Comment by dr0i** [comment] 2015-06-01 11:42
I can see the label now. U2 ?

**Comment by acka47** [comment] 2015-06-01 11:51
+1, closing.

**Comment by acka47** [comment] 2015-06-01 15:08
Reopening.
Here are some more examples with missing GND labels:
http://lobid.org/resource/HT006163820
http://lobid.org/resource/TT001131083
http://lobid.org/resource/HT016993903
http://lobid.org/resource/HT011166589

**Comment by dr0i** [comment] 2015-06-18 14:14
Haha , I thought it was the missing RDFa view ...
Well THAT is now fixed , see e.g. http://test.lobid.org/resource/HT006163820/about.
The missing GND labels are not lables alone but the WHOLE GND entry. Going fix this timely.

**Comment by dr0i** [comment] 2015-06-18 15:21
> The missing GND labels are not lables alone but the WHOLE GND entry.
nonsense. It's only the labels.
However, you did say that you don't want to see these subjects as `dc:subject` but as `subjectChain` , and they *are* subsumed under `subjectChain`:
https://github.com/hbz/lobid/issues/122#issuecomment-78903549
So what now is it you want really?

**Comment by acka47** [comment] 2015-06-19 08:24
> However, you did say that you don't want to see these subjects as `dc:subject` but as `subjectChain` , and they *are* subsumed under `subjectChain`:
https://github.com/hbz/lobid/issues/122#issuecomment-78903549
So what now is it you want really?

This issue isn't about subject labels at all. The problem was that person/corporate body labels for contributors/creators were missing. I saw some time ago this skimming through the [NWBib data](http://lobid.org/nwbib/search?location=&q=*). By now, the data looks good. Whatever you did, the problem is gone (and I hope it will stay that way).

**Comment by acka47** [comment] 2015-06-19 08:30
Closing, as it works for now.

**Closed by acka47** 2015-06-19 08:30 UTC
Labels: working
