### ISSUE TITLE
lobid provides wrong typ for Websites (from edoweb) 

### ISSUE THREAD

**Issue by aquast** [hbz/lobid#313] opened 2016-07-26 06:25 UTC
for instance see http://lobid.org/resource/HT018568995 
"@type" : [ "http://purl.org/dc/terms/BibliographicResource", "http://purl.org/ontology/bibo/Book" ],

seems to me that reason is the missing deatiled information within the catalogue? Do we have anything more than "elektronische resource" at 334? If so we may should provide nothing else than that?

**Comment by acka47** [comment] 2016-07-26 07:41
This may be a duplicate to #152. I would be happy if you found out that the `w` in MAB field 051, element 1 actually means that we deal with an archived web page. See also the lengthy discussion in #99.

Usually, there is at least a `lv:webPageArchived` triple, stating the relation between an archived version and the URL of the web site being archived, see e.g. http://lobid.org/resource?id=TT002234459&format=full. This triple should be created when 652a[-1].a matches `^[Aa][r]` ([morph](https://github.com/lobid/lodmill/blob/e3f4bd5c5f875bc2f226af7c1da2ef7ad166194d/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1331-L1333)) and there is a URL in 655[-eu][ -1].[xy3] ([morph](https://github.com/lobid/lodmill/blob/e3f4bd5c5f875bc2f226af7c1da2ef7ad166194d/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1360-L1370)).

As this is actually the case here (see source snippet below) I am surprised to not find the `webPageArchived` triple in the RDF.

```xml
<datafield tag="652" ind1="a" ind2="1">
  <subfield code="a">Archivierte Online-Ressource</subfield>
</datafield>
<datafield tag="655" ind1="e" ind2="1">
  <subfield code="u">http://www.eifelverein.de/reifferscheid/home/</subfield>
  <subfield code="x">kostenfrei; Langzeitarchivierung</subfield>
</datafield>
```

(The problem might be that there's data in subfield `x`.)

**Comment by aquast** [comment] 2016-07-26 10:17
#152 seems to me a connected issue indeed. Maybe not quite the same. I will review this

**Comment by dr0i** [comment] 2016-07-29 07:31
> (The problem might be that there's data in subfield x.) 

yes

**Comment by aquast** [comment] 2016-08-03 14:13
Speaking with LBZ staff it was clarified that indicator w in position 1 at field 051 can be used to identify web sites. Therefore interpeting field 655 can be skipped in association with edoweb maybe?

**Comment by dr0i** [comment] 2016-08-09 12:50
This is a duplicate of #152. Closing.

**Closed by dr0i** 2016-08-09 12:50 UTC
