### ISSUE TITLE
"publication.description" wrongly treated as link

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#343] opened 2017-06-08 11:46 UTC
See e.g. http://lobid.org/resources/CT003012479 "Inhaltsangabe	Digitalisierte Ausg.".

**Comment by fsteeg** [comment] 2017-06-08 14:25
Duplicate of https://github.com/hbz/lobid-resources/issues/339, closing.

**Closed by fsteeg** 2017-06-08 14:25 UTC
Labels: bug, ready
