### ISSUE TITLE
Missing GND data, labels etc.

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#133] opened 2015-03-19 13:07 UTC
eg. http://lobid.org/resource/HT018216462/about. In fact the labels are in the data, but on a different place. I found the newly added predicate http://purl.org/lobid/lv#nameOfContributingCorporateBody.
Is this supposed to replace the old style inclusion of GND data, like in http://lobid.org/resource/%20HT017297579/about? I'd like to suggest to support both styles until lobid 2.0.

**Comment by acka47** [comment] 2015-03-19 13:14
> Is this supposed to replace the old style inclusion of GND data, like in http://lobid.org/resource/%20HT017297579/about? 
No, it isn't as one needs the `preferedName` for presentation.

> I'd like to suggest to support both styles until lobid 2.0.

That's what we intended to do but obviously it didn't work as planned (and I didn't notice missing labels revieweing the changes.) See the relevant pull request at https://github.com/lobid/lodmill/pull/646.

**Comment by acka47** [comment] 2015-03-19 14:29
After a talk with @jschnasse this looks like a duplicate of #84 84 to me. 

Note that some entries referencing the GND entity http://d-nb.info/gnd/36467-8 include the GND data (e.g. http://lobid.org/resource/%20HT017297579/about) while others don't (e.g. http://lobid.org/resource/HT018216462/about). So this hasn't anything to do with the GND entities referenced. As said in https://github.com/hbz/lobid/issues/84#issuecomment-81704584, this also doesn't have anything to do with the type of an entity. Thus, it seems as the Hadoop job for enriching the data with GND labels randomly omits treating some resources.

**Comment by acka47** [comment] 2015-06-24 13:05
This can also be closed also I got aware of another issue. Obviously, the label of GND entity http://d-nb.info/gnd/36467-8 isn't correctly transformed to RDF, see http://lobid.org/resource?author=36467-8. (Label should be "Rheinland-Pfalz. Statistisches Landesamt" or similar.) Will open another issue for this. Closing this one.

**Closed** 2015-06-24 13:06 UTC
