### ISSUE TITLE
Missing author in http://lobid.org/resource/HT018700720/about

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#233] opened 2015-09-10 12:36 UTC
http://lobid.org/resource/HT018700720/about

Kathrin Otto.... is  listed under contributorLabels, but not as dc:contributor. under dct:contributor only authors with gnd-ids are listed.

**Comment by dr0i** [comment] 2015-09-10 12:48
See hbz/lobid#169 , where it is said :"Use lv properties instead of dc elements for lists of alternate labels."

**Comment by acka47** [comment] 2015-09-10 12:55
To understand the use case behind this: Is your goal to list creator/contributor name for people without GND ID in your HTML presentations? I think this also wasn't possible before deploying #169, was it?

Adding `dc:creator/contributor` (note: DC elements) for these cases seems the way to go here.

**Comment by jschnasse** [comment] 2015-09-10 15:09
> Adding dc:creator/contributor (note: DC elements) for these cases seems the way to go here.
That is what I  would expect.
@dr0i  from my point of view hbz/lobid#169 is a hack to enrich your index data an therefore should use some proprietary lv vocab. hbz/lobid#169 is about alternate labels for authors. This issue is about authors without GND-ID. Lobid should express this two different things differently.

**Comment by acka47** [comment] 2015-09-15 12:22
Duplicate of #154. Closing. (You did it again, @jschnasse.)

**Closed** 2015-09-15 12:22 UTC
Labels: ready
