### ISSUE TITLE
format=short  doesn't return expected value(s)

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#106] opened 2015-01-15 13:20 UTC
Using `format=short` will return only _one_ value even if there are _multiple_ values (array).

This can be reproduced in `ApiTests.java` using the following test:

```
        { "resource?subject=Chemistry&format=short",/* -> */
    "Chemistry & allied sciences" }
```

This query  results in HT000137563, where the first entry of the array

```
[{"@value":"Chemie und zugeordnete Wissenschaften","@language":"de"},{"@value":"Chemistry & allied sciences","@language":"en"}]
```

is stored in the String `Document.matchedField`. So the results for `format=short` is the lonely String `Chemie und zugeordnete Wissenschaften`. The test will fail because it expects `Chemistry & allied sciences`.

Don't know how to deal with it (1. allow storing multiple values in Document.matchedFields, 2. storing only the one that really matched (but what iv there were multiple fields that would match?) 3. ignoring alltogether because it would break some expected behaviour?).

**Comment by fsteeg** [comment] 2015-01-16 19:15
Can't reproduce this as a general issue. In practice your sample seems to work fine:
http://lobid.org/resource?subject=Chemistry&format=short

Seems to be specific to the test or the test data, not a general issue with the `format=short` param.

**Comment by dr0i** [comment] 2015-01-22 08:33
Hm, I guess the sheer size of the documents underlying the lobid API masks that behaviour. Since #104 the test data is taken from the live API - pull the master and try to retrace the issue.
I don't think this is pressing, though, just stumbled about it working on #104.

**Comment by dr0i** [comment] 2015-01-22 08:50
I think it's clearer when you look at [line 197 in Application class](https://github.com/hbz/lobid/blob/2a026688054624b9e9a4568b8f33cf459633383e/app/controllers/Application.java#L197): there is an iteration over documents, getting the string `matchedField` of each document. And this field is a plain string, only holding one value. While there are sometimes more than one values.

**Comment by dr0i** [comment] 2015-07-10 11:02
Bummer. Had to adjust the test lobidResource.searchViaModel() since http://lobid.org/person?id=118554808 has multiple entries for contributors and only the first can be hit, not `Hundt, Theodor` or `Hundt, Josef K.`.

**Comment by acka47** [comment] 2017-07-12 10:32
Won't fix. Closing.

**Closed by acka47** 2017-07-12 10:32 UTC
Labels: bug
